# Generated by Django 5.1.4 on 2025-04-09 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_count',
            field=models.PositiveIntegerField(default=1, help_text='Total number of guests staying', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
