# Generated by Django 5.1.4 on 2025-04-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_refund_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
