# Generated by Django 5.1.4 on 2025-04-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_refunded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('night', 'Per Night'), ('month', 'Per Month')], default='night', help_text='Whether booking is for nightly or monthly stay.', max_length=10),
        ),
    ]
