# Generated by Django 5.1.4 on 2024-12-08 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_apartments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amenity',
            name='apartments',
            field=models.ManyToManyField(related_name='amenities', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='apartmentimage',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apartments.apartment'),
        ),
    ]
