# Generated by Django 5.1.4 on 2025-03-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartmentavailability_propertytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
