# Generated by Django 5.1.4 on 2025-04-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_apartment_latitude_apartment_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='bookings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
