# Generated by Django 5.1.4 on 2025-04-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_apartment_average_rating_apartment_bookings_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per night in the default currency.', max_digits=8),
        ),
    ]
