# Generated by Django 5.1.4 on 2025-05-26 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_apartment_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='max_guests',
            field=models.IntegerField(default=2, help_text='Maximum number of guests allowed.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, help_text='Cost per month for long-term rentals.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per night for short-term stays.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
